import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import "@radix-ui/themes/styles.css";
import './globals.css'
import { getMessages } from "next-intl/server";
import localFont from "next/font/local";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Theme } from '@radix-ui/themes';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  //   // Providing all messages to the client
//   // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Theme accentColor='gold'>
          <Navbar/>
          {children}
          <Footer/>
          </Theme>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}

